### ISSUE TITLE
error C2974: “Ink::TValue”:“T”的 模板 参数无效，应为类型

### ISSUE THREAD

**Issue by questionkiller** [The-Chinese-Room/Inkpot#103]
当我尝试添加到5.4中 报错
G:\UE_5.4\Engine\Source\Runtime\Core\Public\Containers\Array.h(3173): error C2974: “Ink::TValue”:“T”的 模板 参数无效，应为类型
1>G:\Git\tdrpg\Plugins\Inkpot\Source\InkPlusPlus\Public\Ink\Value.h(71): note: 参见“Ink::TValue”的声明
1>G:\UE_5.4\Engine\Source\Runtime\Core\Public\Containers\Array.h(3173): note: 模板实例化上下文(最早的实例化上下文)为
1>G:\Git\tdrpg\Plugins\Inkpot\Source\InkPlusPlus\Public\Ink\NativeFunctionCall.h(78): note: 查看对正在编译的 类 模板 实例化“TArray<TSharedPtr<Ink::FValue,ESPMode::ThreadSafe>,FDefaultAllocator>”的引用
1>G:\UE_5.4\Engine\Source\Runtime\Core\Public\Containers\Array.h(419): note: 在编译 类 模板 成员函数“TArray<TSharedPtr<Ink::FValue,ESPMode::ThreadSafe>,FDefaultAllocator>::TArray(std::initializer_list<InElementType>)”时
1>        with
1>        [
1>            InElementType=TSharedPtr<Ink::FValue,ESPMode::ThreadSafe>
1>        ]
1>G:\Git\tdrpg\Plugins\Inkpot\Source\InkPlusPlus\Private\Ink\NativeFunctionCall.cpp(214): note: 请参阅 "Ink::FNativeFunctionCall::CallBinaryListOperation" 中对 "TArray<TSharedPtr<Ink::FValue,ESPMode::ThreadSafe>,FDefaultAllocator>::TArray" 的第一个引用
1>G:\UE_5.4\Engine\Source\Runtime\Core\Public\Containers\Array.h(424): note: 查看对正在编译的函数 模板 实例化“void TArray<TSharedPtr<Ink::FValue,ESPMode::ThreadSafe>,FDefaultAllocator>::CopyToEmpty<_Elem,int>(const OtherElementType *,OtherSizeType,int)”的引用
1>        with
1>        [
1>            _Elem=TSharedPtr<Ink::FValue,ESPMode::ThreadSafe>,
1>            OtherElementType=TSharedPtr<Ink::FValue,ESPMode::ThreadSafe>,
1>            OtherSizeType=int
1>        ]

**Comment by questionkiller** [comment]
我查看了已解决问题里有相同的问题 但是更新编译器版本 并不能解决这个问题

**Comment by questionkiller** [comment]
I created a new project and successfully compiled it after importing the plugin without modifying the compiler. However, the old project doesn't work. Could this be related to using Git for project management?

**Comment by TCR-Nick** [comment]
ok, that's interesting, the solution may be simply to clear out the intermediate folders.
I don't think it would be git.

As you have fixed this I'm going to close the issue.
