### ISSUE TITLE
Unable to package 'Shipping' game or InkpotDemo

### ISSUE THREAD

**Issue by kgeisler** [The-Chinese-Room/Inkpot#31]
The Unreal module "Settings" seems to prevent creating a Shipping-configured package of the game. Is there a way to support this?

**Comment by kgeisler** [comment]
Should "Settings" be added here and removed from PublicDependencyModuleNames?
`PublicIncludePathModuleNames.AddRange(
	new string[] 
	{
		"Settings",
	}
);`

**Comment by TCR-Nick** [comment]
@kgeisler I've removed settings altogether as that code was not used

**Comment by TCR-Nick** [comment]
This will now compile in shipping.
