### ISSUE TITLE
TempInkFile.ink could not be opened

### ISSUE THREAD

**Issue by gregorhcs** [The-Chinese-Room/Inkpot#33]
I got the following warning after dragging a new ink file into the browser (not named TempInkFile.ink):

`Inkpot: Warning: CompileInkString - ../../../../../../../Projects/InkpotDemo/InkpotDemo/Plugins/Inkpot/Intermediate/InkCommandLine/1/2/TempInkFile.ink failed to compile ink string. Error Could not open file ''../../../../../../../Projects/InkpotDemo/InkpotDemo/Plugins/Inkpot/Intermediate/InkCommandLine/1/2/TempInkFile.ink''`

Already tried adding safety apostrophes (see 1 below) and a check ensuring that the temp file already exists (see 2 below), didn't help.
![grafik](https://github.com/The-Chinese-Room/InkpotDemo/assets/42077794/ff6ef95e-c4e8-435c-8549-69fa5635e6f3)

**Comment by gregorhcs** [comment]
Additional info: if I run
`"../../../../../../../Projects/InkpotDemo/InkpotDemo/Plugins/Inkpot/ThirdParty/InkCommandLine/inklecate.exe" -j "../../../../../../../Projects/InkpotDemo/InkpotDemo/Plugins/Inkpot/Intermediate/InkCommandLine/1/2/TempInkFile.ink"`
from the command line, I get some output:
`{"compile-success": true}
{"issues":[]}{"export-complete": true}`

**Comment by gregorhcs** [comment]
Fixed it by adding a line that collapses relative directories for the TempInkFile, I'll maybe make a pull request :)

**Comment by Stoeoeoe** [comment]
Just in case somebody still has this issue after applyingthis fix: For me, inklecate.exe did not compile the file because there was a space in my project's path. Moving the project to a location without spaces solved it.

**Comment by TCR-Nick** [comment]
pulled :)
