### ISSUE TITLE
Save/Load Alternative to JSON Serialisation? 

### ISSUE THREAD

**Issue by DorminVR** [The-Chinese-Room/Inkpot#37]
> You will note that 2 of the tests fail, these are the JSON serialisation tests & we simply did not need to implement them in our usage case.

So I'm aware that JSON serialisation isn't part of this plugin, and this isn't technically an issue- I just don't know where else to post this discussion. I would love to use plugin for a translation of [a game I released](https://store.steampowered.com/app/2396620/A_Hint_of_Purple/), however I don't know how to implement save/load functionality without JSON serialisation. 

1. Is there a way to create save/load functionality of the ink story state using Unreal blueprints? (Without relying on JSON serialisation or diving into C++)
2. Is anyone thinking about adding JSON serialisation support? If so please let me know, as I'd be interested in commissioning this feature. 

(Re 2: I'm aware that The Chinese Room doesn't have current plans to add this feature, so posing this question more to the community)

**Comment by kgeisler** [comment]
I'm also interested in solutions to this problem. 

I tried using the ToJson() function from the StoryState in C++, but run into check(CanWriteValueWithoutIdentifier()); asserts from the JsonWriter.

**Comment by kgeisler** [comment]
Ok, I spent a few hours looking into some preliminary solutions. I don't really use GitHub, so apologies for the code snippets.

This at least saves/loads visitCounts and variables correctly for me, currently enough for a prototyping use case.

In Ink/VariableState.cpp I made the following changes.
- Use SetGlobal function to set the _defaultGlobalVariables map.
- Write "variablesState" prefix before variables.
- Write variable names before values.

```
void Ink::FVariableState::SetJsonToken(const TMap<FString, TSharedPtr<FJsonValue>>& JsonToken)
{
	_globalVariables.Reset();

	for (const TPair<FString, TSharedPtr<Ink::FObject>>& variablePair : _defaultGlobalVariables)
	{
		const FString variableName = variablePair.Key;

		const TSharedPtr<FJsonValue>* loadedTokenPtrPtr = JsonToken.Find(variableName);
		if (loadedTokenPtrPtr != nullptr && (*loadedTokenPtrPtr).IsValid())
		{
			SetGlobal(variableName, Ink::FJsonSerialisation::JsonTokenToRuntimeObject(**loadedTokenPtrPtr));
		}
		else
		{
			SetGlobal(variableName, variablePair.Value);
		}
	}
}

void Ink::FVariableState::WriteJson(TJsonWriter<>* Writer)
{
	Writer->WriteIdentifierPrefix("variablesState");
	Writer->WriteObjectStart();
	for (const auto& pair: _globalVariables)
	{
		const FString key = pair.Key;
		const TSharedPtr<FObject> value = pair.Value;

		if (_dontSaveDefaultValues)
		{
			// Don't write out values that are the same as the default global values
			TSharedPtr<Ink::FObject>* defaultValuePtr = _defaultGlobalVariables.Find(key);
			if (defaultValuePtr != nullptr && RuntimeObjectsEqual(value, *defaultValuePtr))
			{
				continue;
			}
		}

		Writer->WriteIdentifierPrefix(key);
		Ink::FJsonSerialisation::WriteRuntimeObject(Writer, value);
	}
	Writer->WriteObjectEnd();
}
```
And in StoryState.cpp made the following changes:

- Call writer->Close(); in FStoryState::ToJson();
- Fix an assert direction requiring saveVersion be **higher** in value than MinCompatibleLoadVersion
- Remove Writer->WriteObjectStart(); and Writer->WriteObjectEnd(); from FStoryState::WriteProperty
- Remove writing Flows/callstacks to JSON for now.

```
FString Ink::FStoryState::ToJson() const
{
	FString jsonString;
	TSharedPtr<TJsonWriter<>> writer = TJsonWriterFactory<>::Create(&jsonString);
	WriteJson(writer.Get());
	writer->Close();
	return jsonString;
}

void Ink::FStoryState::LoadJSONObj(const FJsonObject& InJSONObj)
{
	const TSharedPtr<FJsonValue> jSaveVersion = InJSONObj.TryGetField(TEXT("inkSaveVersion"));
	checkf(jSaveVersion.IsValid(), TEXT("ink save format incorrect, can't load!"));

	const int32 saveVersion = static_cast<int32>(jSaveVersion->AsNumber());
	checkf(saveVersion > MinCompatibleLoadVersion, TEXT("Ink save format isn't compatible with the current version (saw '%d', but minimum is '%d'), so can't load."), saveVersion, MinCompatibleLoadVersion);

	// REMAINDER NOT POSTED
}

template<typename T>
void Ink::FStoryState::WriteProperty(TJsonWriter<>* Writer, const FString& PropertyName, T PropertyValue) const
{
	Writer->WriteIdentifierPrefix(PropertyName);
	//Writer->WriteObjectStart();
	Writer->WriteValue(PropertyValue);
	//Writer->WriteObjectEnd();
}
```

I have not figured out the correct JSON formatting for Flows, so I just commented it out for now. I don't seem to need it.

```
void Ink::FStoryState::WriteJson(TJsonWriter<>* Writer) const
{
	Writer->WriteObjectStart();

	/*
	// Flows
	Writer->WriteIdentifierPrefix("flows");
	Writer->WriteObjectStart();

	if (NamedFlows.IsValid()) {
		// Multi-flow
		for (const TTuple<FString, TSharedPtr<FFlow>>& namedFlow : *NamedFlows)
		{
			namedFlow.Value->WriteJSON(Writer);
		}
	}
	else {
		// Single flow
		CurrentFlow->WriteJSON(Writer);
	}

	Writer->WriteObjectEnd();
	Writer->WriteObjectEnd(); // end of flows

	WriteProperty(Writer, "currentFlowName", CurrentFlow->GetName());*/
	VariableState->WriteJson(Writer);

	// REMAINDER NOT POSTED
}
```

Then I simply have my blueprint utility functions
```

// *.Build.cs
// PublicDependencyModuleNames.AddRange(new string[] { "Inkpot", "InkPlusPlus" });

#include "Inkpot/Inkpot.h"
#include "Inkpot/InkpotStory.h"
#include "Ink/StoryState.h" 

FString USaveGameEditorUtilities::ExportInkpotStoryToString(UInkpotStory* InkpotStory)
{
	FString returnStr;

	if (InkpotStory)
	{
		returnStr = InkpotStory->GetStoryInternal()->GetStoryState()->ToJson();
	}

	return returnStr;
}

bool USaveGameEditorUtilities::ImportInkpotStoryFromString(UInkpotStory* InkpotStory, const FString& JsonString)
{
	if (InkpotStory)
	{
		InkpotStory->GetStoryInternal()->GetStoryState()->LoadJSON(JsonString);
		return true;
	}

	return false;
}
```

**Comment by TCR-Nick** [comment]
as of 0.3.21 Inkpot now fully supports serialisation.
thanks for digging in @kgeisler :)

**Comment by DorminVR** [comment]
Ya'll are amazing for adding Json serialization support. Thank you! 

I've been playing around with the latest version and I am running into some crashes, it appears that Json serialization works just fine if I call the To Json function immediately after starting the story. But after progressing the story, by selecting a choice, calling the To Json function crashes Unreal. These are the errors I'm running into, any ideas? 

`Assertion failed: CanWriteValueWithoutIdentifier() [File:D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Json\Public\Serialization\JsonWriter.h] [Line: 193]

UnrealEditor_InkPlusPlus!Ink::FStoryState::WriteJson() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\InkPlusPlus\Private\Ink\StoryState.cpp:689]
UnrealEditor_InkPlusPlus!Ink::FStoryState::ToJson() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\InkPlusPlus\Private\Ink\StoryState.cpp:52]
UnrealEditor_Inkpot!UInkpotStory::ToJSON() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\Inkpot\Private\Inkpot\InkpotStory.cpp:611]
UnrealEditor_Inkpot!UInkpotStory::execToJSON() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Intermediate\Build\Win64\UnrealEditor\Inc\Inkpot\UHT\InkpotStory.gen.cpp:383]
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_Inkpot!TMulticastScriptDelegate<FNotThreadSafeDelegateMode>::ProcessMulticastDelegate<UObject>() [D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Core\Public\UObject\ScriptDelegates.h:900]
UnrealEditor_Inkpot!FOnStoryContinue_DelegateWrapper() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Intermediate\Build\Win64\UnrealEditor\Inc\Inkpot\UHT\InkpotStory.gen.cpp:71]
UnrealEditor_Inkpot!UInkpotStory::OnContinueInternal() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\Inkpot\Private\Inkpot\InkpotStory.cpp:333]
UnrealEditor_Inkpot!TBaseUObjectMethodDelegateInstance<0,UInkpotStory,void __cdecl(void),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:667]
UnrealEditor_InkPlusPlus!Ink::FStory::ContinueInternal() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\InkPlusPlus\Private\Ink\Story.cpp:342]
UnrealEditor_InkPlusPlus!Ink::FStory::Continue() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\InkPlusPlus\Private\Ink\Story.cpp:204]
UnrealEditor_Inkpot!UInkpotStory::Continue() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\Inkpot\Private\Inkpot\InkpotStory.cpp:80]
UnrealEditor_Inkpot!UInkpotStory::execContinue() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Intermediate\Build\Win64\UnrealEditor\Inc\Inkpot\UHT\InkpotStory.gen.cpp:699]
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_Inkpot!TMulticastScriptDelegate<FNotThreadSafeDelegateMode>::ProcessMulticastDelegate<UObject>() [D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Core\Public\UObject\ScriptDelegates.h:900]
UnrealEditor_Inkpot!FOnMakeChoice_DelegateWrapper() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Intermediate\Build\Win64\UnrealEditor\Inc\Inkpot\UHT\InkpotStory.gen.cpp:121]
UnrealEditor_Inkpot!UInkpotStory::OnMakeChoiceInternal() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\Inkpot\Private\Inkpot\InkpotStory.cpp:344]
UnrealEditor_Inkpot!TBaseUObjectMethodDelegateInstance<0,UInkpotStory,void __cdecl(TSharedPtr<Ink::FChoice,1>),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:665]
UnrealEditor_InkPlusPlus!TMulticastDelegateBase<FDefaultDelegateUserPolicy>::Broadcast<IBaseDelegateInstance<void __cdecl(TSharedPtr<Ink::FChoice,1>),FDefaultDelegateUserPolicy>,TSharedPtr<Ink::FChoice,1> >() [D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Core\Public\Delegates\MulticastDelegateBase.h:254]
UnrealEditor_InkPlusPlus!Ink::FStory::ChooseChoiceIndex() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\InkPlusPlus\Private\Ink\Story.cpp:1633]
UnrealEditor_Inkpot!UInkpotStory::ChooseChoice() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\Inkpot\Private\Inkpot\InkpotStory.cpp:132]
UnrealEditor_Inkpot!UInkpotStory::execChooseChoice() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Intermediate\Build\Win64\UnrealEditor\Inc\Inkpot\UHT\InkpotStory.gen.cpp:644]
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
user32
user32
UnrealEditor_ApplicationCore
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll`

**Comment by TCR-Nick** [comment]
Hmm, ok, this got missed by the tests.
I'll take a look in the next day or so.

**Comment by TCR-Nick** [comment]
@DorminVR this is now fixed, and a few more tests added. 
Shout if you find more :)

**Comment by DorminVR** [comment]
Amazing, appreciate the quick turnaround Nick! So did some testing with the changes, and I'm getting a bit mixed up trying to keep track of things. Initially I found that this resolved the crash, but resulted in an empty string. Now when testing the engine appears to be crashing everytime, so I'm not entirely sure what's happening. Here's the breakdown of what's happening to the best of my knowledge. 

Calling To Json function immediately after starting the story
- Returns a string with the story state as expected

Calling To Json function after choosing a choice in the story
- Initially didn't crash the engine, after testing repeatedly now crashes the engine reliably
- Returns an empty string

Here's the error messages:

Assertion failed: CanWriteValueWithoutIdentifier() [File:D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Json\Public\Serialization\JsonWriter.h] [Line: 193]

UnrealEditor_InkPlusPlus!Ink::FStoryState::WriteJson() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\InkPlusPlus\Private\Ink\StoryState.cpp:689]
UnrealEditor_InkPlusPlus!Ink::FStoryState::ToJson() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\InkPlusPlus\Private\Ink\StoryState.cpp:52]
UnrealEditor_Inkpot!UInkpotStory::ToJSON() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\Inkpot\Private\Inkpot\InkpotStory.cpp:611]
UnrealEditor_Inkpot!UInkpotStory::execToJSON() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Intermediate\Build\Win64\UnrealEditor\Inc\Inkpot\UHT\InkpotStory.gen.cpp:383]
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_Inkpot!TMulticastScriptDelegate<FNotThreadSafeDelegateMode>::ProcessMulticastDelegate<UObject>() [D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Core\Public\UObject\ScriptDelegates.h:900]
UnrealEditor_Inkpot!FOnStoryContinue_DelegateWrapper() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Intermediate\Build\Win64\UnrealEditor\Inc\Inkpot\UHT\InkpotStory.gen.cpp:71]
UnrealEditor_Inkpot!UInkpotStory::OnContinueInternal() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\Inkpot\Private\Inkpot\InkpotStory.cpp:333]
UnrealEditor_Inkpot!TBaseUObjectMethodDelegateInstance<0,UInkpotStory,void __cdecl(void),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:667]
UnrealEditor_InkPlusPlus!Ink::FStory::ContinueInternal() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\InkPlusPlus\Private\Ink\Story.cpp:342]
UnrealEditor_InkPlusPlus!Ink::FStory::Continue() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\InkPlusPlus\Private\Ink\Story.cpp:204]
UnrealEditor_Inkpot!UInkpotStory::Continue() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\Inkpot\Private\Inkpot\InkpotStory.cpp:80]
UnrealEditor_Inkpot!UInkpotStory::execContinue() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Intermediate\Build\Win64\UnrealEditor\Inc\Inkpot\UHT\InkpotStory.gen.cpp:699]
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_Inkpot!TMulticastScriptDelegate<FNotThreadSafeDelegateMode>::ProcessMulticastDelegate<UObject>() [D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Core\Public\UObject\ScriptDelegates.h:900]
UnrealEditor_Inkpot!FOnStoryContinue_DelegateWrapper() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Intermediate\Build\Win64\UnrealEditor\Inc\Inkpot\UHT\InkpotStory.gen.cpp:71]
UnrealEditor_Inkpot!UInkpotStory::OnContinueInternal() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\Inkpot\Private\Inkpot\InkpotStory.cpp:333]
UnrealEditor_Inkpot!TBaseUObjectMethodDelegateInstance<0,UInkpotStory,void __cdecl(void),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:667]
UnrealEditor_InkPlusPlus!Ink::FStory::ContinueInternal() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\InkPlusPlus\Private\Ink\Story.cpp:342]
UnrealEditor_InkPlusPlus!Ink::FStory::Continue() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\InkPlusPlus\Private\Ink\Story.cpp:204]
UnrealEditor_Inkpot!UInkpotStory::Continue() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\Inkpot\Private\Inkpot\InkpotStory.cpp:80]
UnrealEditor_Inkpot!UInkpotStory::execContinue() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Intermediate\Build\Win64\UnrealEditor\Inc\Inkpot\UHT\InkpotStory.gen.cpp:699]
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_Inkpot!TMulticastScriptDelegate<FNotThreadSafeDelegateMode>::ProcessMulticastDelegate<UObject>() [D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Core\Public\UObject\ScriptDelegates.h:900]
UnrealEditor_Inkpot!FOnStoryContinue_DelegateWrapper() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Intermediate\Build\Win64\UnrealEditor\Inc\Inkpot\UHT\InkpotStory.gen.cpp:71]
UnrealEditor_Inkpot!UInkpotStory::OnContinueInternal() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\Inkpot\Private\Inkpot\InkpotStory.cpp:333]
UnrealEditor_Inkpot!TBaseUObjectMethodDelegateInstance<0,UInkpotStory,void __cdecl(void),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:667]
UnrealEditor_InkPlusPlus!Ink::FStory::ContinueInternal() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\InkPlusPlus\Private\Ink\Story.cpp:342]
UnrealEditor_InkPlusPlus!Ink::FStory::Continue() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\InkPlusPlus\Private\Ink\Story.cpp:204]
UnrealEditor_Inkpot!UInkpotStory::Continue() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\Inkpot\Private\Inkpot\InkpotStory.cpp:80]
UnrealEditor_Inkpot!UInkpotStory::execContinue() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Intermediate\Build\Win64\UnrealEditor\Inc\Inkpot\UHT\InkpotStory.gen.cpp:699]
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_Inkpot!TMulticastScriptDelegate<FNotThreadSafeDelegateMode>::ProcessMulticastDelegate<UObject>() [D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Core\Public\UObject\ScriptDelegates.h:900]
UnrealEditor_Inkpot!FOnMakeChoice_DelegateWrapper() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Intermediate\Build\Win64\UnrealEditor\Inc\Inkpot\UHT\InkpotStory.gen.cpp:121]
UnrealEditor_Inkpot!UInkpotStory::OnMakeChoiceInternal() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\Inkpot\Private\Inkpot\InkpotStory.cpp:344]
UnrealEditor_Inkpot!TBaseUObjectMethodDelegateInstance<0,UInkpotStory,void __cdecl(TSharedPtr<Ink::FChoice,1>),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:665]
UnrealEditor_InkPlusPlus!TMulticastDelegateBase<FDefaultDelegateUserPolicy>::Broadcast<IBaseDelegateInstance<void __cdecl(TSharedPtr<Ink::FChoice,1>),FDefaultDelegateUserPolicy>,TSharedPtr<Ink::FChoice,1> >() [D:\UnrealEngine\UE_5.3\Engine\Source\Runtime\Core\Public\Delegates\MulticastDelegateBase.h:254]
UnrealEditor_InkPlusPlus!Ink::FStory::ChooseChoiceIndex() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\InkPlusPlus\Private\Ink\Story.cpp:1633]
UnrealEditor_Inkpot!UInkpotStory::ChooseChoice() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Source\Inkpot\Private\Inkpot\InkpotStory.cpp:132]
UnrealEditor_Inkpot!UInkpotStory::execChooseChoice() [D:\UnrealProjects\LockedIn_Github\Plugins\Inkpot\Intermediate\Build\Win64\UnrealEditor\Inc\Inkpot\UHT\InkpotStory.gen.cpp:644]
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
user32
user32
UnrealEditor_ApplicationCore
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll

**Comment by TCR-Nick** [comment]
Thanks for posting the logs, very helpful.
Can you post the ink script that causes this ( or similar ), as that code is what got fixed in the last update. 

In StoryState.cpp, line 689 it should look like this

![image](https://github.com/The-Chinese-Room/Inkpot/assets/141139646/d9fc5d1f-28da-4225-b918-b07211673702)

**Comment by DorminVR** [comment]
Total user error on my end, I hadn't rebuilt from Visual Studio. Everything is working as expected now and it's amazing, so happy to have save/load working for my game. Thanks so much!
