### ISSUE TITLE
Unable to import Inkpot files to Unreal Project when project path uses spaces.

### ISSUE THREAD

**Issue by kgeisler** [The-Chinese-Room/Inkpot#39]
One of our team members was unable to import .ink files to the project until we realized the project path had spaces in it. Seems that it could not find the temp files created in Plugins\Inkpot\Intermediate\InkCommandLine\1\2

Removing the spaces solved the issue, but figured I would report this to be investigated.

**Comment by huntsfromshadow** [comment]
This is true even if it is a top level directory and the source file is showing a relative path.
Eg.
c:\code\unreal projects\TestProject

The source file is in c:\code\unreal projects\TestProject\StorySource
UI shows a relative link:
../../StorySource/MainFile.ink

Started working when I renamed unreal projects to unreal_projects

**Comment by TCR-Nick** [comment]
this is now fixed
