### ISSUE TITLE
Unable to import ink files that INCLUDE other files

### ISSUE THREAD

**Issue by kzuhn** [The-Chinese-Room/Inkpot#40]
I'm trying to create a master ink file that includes my other files for the sake of making it possible to communicate between all of them (and to avoid having all text stored in one massive story file).

<img width="407" alt="image" src="https://github.com/The-Chinese-Room/Inkpot/assets/150172109/9c9546c1-7e06-40e1-976e-4560518da44f">

However, any time I try to import it into Unreal, it fails with the following message.
{"issues":["ERROR: 'TempInkFile.ink' line 1: Failed to load: 'Sheriff.ink'","ERROR: 'TempInkFile.ink' line 2: Failed to load: 'TestFile.ink'"]}: 

My assumption so far is that it can't load the files because they aren't present in the temp folder where the compile is happening. Trying to place the files in the temp folder doesn't resolve it, since they just get deleted when the compile begins. Is there any way around this?

**Comment by TCR-Nick** [comment]
This is now fixed.
The copy step has been removed and the files are compiled in situ, output is captured in scratch folder.
