### ISSUE TITLE
Inkpot Plugin not appearing in packaged builds? 

### ISSUE THREAD

**Issue by DorminVR** [The-Chinese-Room/Inkpot#65]
Everything is working just fine in editor, however when I package a shipping build for Windows I'm not seeing the text from my story appear. I believe the plugin isn't being included with the build, but I'm not sure why. 

Here's how I'm packaging my build:
![package](https://github.com/The-Chinese-Room/Inkpot/assets/69361026/29a5188f-398e-4192-92c7-14645cfc2a47)

And here is the directory where I was expecting to see Inkpot related files, but there appear to be none:
![buildirectory](https://github.com/The-Chinese-Room/Inkpot/assets/69361026/9aa97a5e-d079-4663-b337-55e9c10cda74)

Here is my [build on Google Drive](https://drive.google.com/drive/u/1/folders/1Rm3Ap8mXBcH_uTztVYTOj-wMn-Ska7ru) if it's helpful to poke around the directory. 

Troubleshooting steps taken so far:
- I've tried manually copying Inkpot DLLs from the Win64 folder to the packaged build
- I've double checked that the plugin is indeed enabled
- Built the project off the C Drive, as opposed to an external drive (People on the Unreal forums have reported this fixing issues with plugins not being packaged correctly)
- Enabled the plugin by default on all projects (Another culprit according to some people online that can cause plugins to not get packaged correctly)

Any help would be much appreciated, thank you! This plugin has been amazing to work with so far.

**Comment by TCR-Nick** [comment]
When unreal creates a packaged build all the code is combined for the game, the DLLs for plugins only exist in development and debug.
If you check the logs ( in a dev\debug build; <your packaged folder>\Windows\InkpotDemo\Saved\Logs ) then you'll see that there should be output from Inkpot.
What has happened here is that there is a timing issue for BeginPlay between the gamemode and the level blueprint.
Adding in a DelayUntilNextTick on the level blue print begin play seems to fix. 

![image](https://github.com/The-Chinese-Room/Inkpot/assets/141139646/660de2bb-4258-42c3-818b-28bb4fe8223d)

**Comment by DorminVR** [comment]
Great find, that fixed the issue for me. Now I've got Inkpot working in my game with full feature parity, appreciate all your help!

With Inkpot fully implemented I'll finally be able to release a localized version of the game for a new audience. (The Unreal Ink plugin I was previously using didn't support non-ascii characters). Thanks again for the quick replies and helping me track down the cause of these issues.

**Comment by TCR-Nick** [comment]
Glad you got it sorted.
