### ISSUE TITLE
Inkpot, InkPlusPlus, and InkpotEditor not building

### ISSUE THREAD

**Issue by davidtveraas** [The-Chinese-Room/Inkpot#67]
![Inky](https://github.com/The-Chinese-Room/Inkpot/assets/52186959/d38bae33-6d4e-4adf-9568-06d56274f1e0)
![Inky2](https://github.com/The-Chinese-Room/Inkpot/assets/52186959/7f85ebab-588e-4c71-a39a-5f8cb594c262)
I have followed the steps to install the Plugin, I have the .NET version and Visual Studio 2022 as listed. I'm unfamiliar with how I can build these three from source. Any advice? Thank you for your help.

**Comment by davidtveraas** [comment]
[Arabian_Nights.log](https://github.com/The-Chinese-Room/Inkpot/files/13926489/Arabian_Nights.log)
My UE 5.3 project log

**Comment by HenryHa993** [comment]
Hi, any advice on how to fix this as I have had the same issues.
